enforce_ratio:True
default_card:V100
enforce_min:True
enforce_max:True
partition:es1
{"name":"GRTX2080TI", "min":1, "max":2, "weight":"1"}
{"name":"V100", "min":2, "max":8, "weight":"2"}
{"name":"A40", "min":2, "max":16, "weight":"5"}