EnforceRatio:True
DefaultCard:V100
EnforceMin:True
EnforceMax:True
Partition:es1
{"name":"2080ti", "min":2, "max":2, "weight":"2"}
{"name":"v100", "min":2, "max":8, "weight":"3"}
{"name":"a40", "min":2, "max":16, "weight":"5"}