[enable] # comment
loremipsum = false # comment asdf
enableGresRatioPlugin = true # comment
loremipsum = false

# random comment
[gresratio] #no comments allowed below this line
enforce_ratio:true
default_card:V100
enforce_min:true
enforce_max:true
partition:es1

[gresratio.cards]
GRTX2080TI = {min = 1, max = 2, weight = 1.0}
V100 = {min = 2, max = 8, weight = 1.0}
A40 = {min = 2, max = 16, weight = 5.0}

[loremipsum]
blahblah = True
loremipsum = [1,2,3]

